//
// Generated file, do not edit! Created by opp_msgtool 6.3 from src/repaodv/repAodv.msg.
//

#ifndef __INET__AODV_REPAODV_M_H
#define __INET__AODV_REPAODV_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {
namespace aodv {

class AodvForwardAck;
struct TrustShareEntry;
class AodvTrustShare;

}  // namespace aodv
}  // namespace inet

#include "inet/routing/aodv/AodvControlPackets_m.h" // import inet.routing.aodv.AodvControlPackets


namespace inet {
namespace aodv {

/**
 * Class generated from <tt>src/repaodv/repAodv.msg:6</tt> by opp_msgtool.
 * <pre>
 * class AodvForwardAck extends AodvControlPacket
 * {
 *     uint64_t packetId;
 *     L3Address originSender;
 * }
 * </pre>
 */
class AodvForwardAck : public ::inet::aodv::AodvControlPacket
{
  protected:
    uint64_t packetId = 0;
    ::inet::L3Address originSender;

  private:
    void copy(const AodvForwardAck& other);

  protected:
    bool operator==(const AodvForwardAck&) = delete;

  public:
    AodvForwardAck();
    AodvForwardAck(const AodvForwardAck& other);
    virtual ~AodvForwardAck();
    AodvForwardAck& operator=(const AodvForwardAck& other);
    virtual AodvForwardAck *dup() const override {return new AodvForwardAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint64_t getPacketId() const;
    virtual void setPacketId(uint64_t packetId);

    virtual const ::inet::L3Address& getOriginSender() const;
    virtual ::inet::L3Address& getOriginSenderForUpdate() { handleChange();return const_cast<::inet::L3Address&>(const_cast<AodvForwardAck*>(this)->getOriginSender());}
    virtual void setOriginSender(const ::inet::L3Address& originSender);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AodvForwardAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AodvForwardAck& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from src/repaodv/repAodv.msg:11 by opp_msgtool.
 */
struct TrustShareEntry
{
    TrustShareEntry();
    ::inet::L3Address nodeId;
    double reputationScore = 0;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const TrustShareEntry& a);
void __doUnpacking(omnetpp::cCommBuffer *b, TrustShareEntry& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TrustShareEntry& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TrustShareEntry& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>src/repaodv/repAodv.msg:16</tt> by opp_msgtool.
 * <pre>
 * class AodvTrustShare extends AodvControlPacket
 * {
 *     TrustShareEntry entries[];
 * }
 * </pre>
 */
class AodvTrustShare : public ::inet::aodv::AodvControlPacket
{
  protected:
    TrustShareEntry *entries = nullptr;
    size_t entries_arraysize = 0;

  private:
    void copy(const AodvTrustShare& other);

  protected:
    bool operator==(const AodvTrustShare&) = delete;

  public:
    AodvTrustShare();
    AodvTrustShare(const AodvTrustShare& other);
    virtual ~AodvTrustShare();
    AodvTrustShare& operator=(const AodvTrustShare& other);
    virtual AodvTrustShare *dup() const override {return new AodvTrustShare(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setEntriesArraySize(size_t size);
    virtual size_t getEntriesArraySize() const;
    virtual const TrustShareEntry& getEntries(size_t k) const;
    virtual TrustShareEntry& getEntriesForUpdate(size_t k) { handleChange();return const_cast<TrustShareEntry&>(const_cast<AodvTrustShare*>(this)->getEntries(k));}
    virtual void setEntries(size_t k, const TrustShareEntry& entries);
    virtual void insertEntries(size_t k, const TrustShareEntry& entries);
    [[deprecated]] void insertEntries(const TrustShareEntry& entries) {appendEntries(entries);}
    virtual void appendEntries(const TrustShareEntry& entries);
    virtual void eraseEntries(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AodvTrustShare& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AodvTrustShare& obj) {obj.parsimUnpack(b);}


}  // namespace aodv
}  // namespace inet


namespace omnetpp {

template<> inline inet::aodv::AodvForwardAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodv::AodvForwardAck*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::aodv::TrustShareEntry *p) {return any_ptr(p);}
template<> inline inet::aodv::TrustShareEntry *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::aodv::TrustShareEntry>(); }
template<> inline inet::aodv::AodvTrustShare *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodv::AodvTrustShare*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET__AODV_REPAODV_M_H

